const GET_DOGS = 'GET_DOGS';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const GET_DOGS_BY_NAME = 'GET_DOGS_BY_NAME';
const GET_DETAIL = 'GET_DETAIL';
const ADD_DOG = 'ADD_DOG'
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
const FILTER_BY_TEMPERAMENTS = 'FILTER_BY_TEMPERAMENTS'
const CLEAR_STATE = 'CLEAR_STATE';

module.exports = {
    GET_DOGS,
    GET_TEMPERAMENTS,
    GET_DOGS_BY_NAME,
    GET_DETAIL,
    ADD_DOG,
    ORDER_BY_NAME,
    ORDER_BY_WEIGHT,
    FILTER_BY_TEMPERAMENTS,
    CLEAR_STATE
}